version: "3.4"
volumes:
  elasticsearch-data:
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
  rabbitmqexample.api:
    image: ${DOCKER_REGISTRY-}rabbitmqexampleapi
    build:
      context: .
      dockerfile: RabbitMQExample.API/Dockerfile
    depends_on:
      - bus
  bus:
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    image: rabbitmq:3-management
    container_name: rabbit-bus
    ports:
      - "999:5672"
      - "15000:15672"
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
